# Generated by Django 5.2.1 on 2026-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restapi',
            fields=[
                ('id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50, unique=True)),
                ('company_code', models.CharField(blank=True, help_text='Format: 2 alphabets, 2 numbers, ends with E or N (e.g., AB12E)', max_length=50, null=True, unique=True)),
                ('strength', models.IntegerField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
