# Generated by Django 5.2.1 on 2026-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restapi',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restapi',
            name='strength',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
